### ISSUE TITLE
Asking for end-to-end Nexus implementation

### ISSUE THREAD

**Issue by Runnoob123** [zju-abclab/NEXUS#1]
Sorry for bothering you, I would like to ask whether current NEXUS repository contains the end-to-end bert network implementation code based on homomorphic encryption, thanks a lot

**Comment by ttttonyhe** [comment]
Hi @Runnoob123, we currently do not provide an end-to-end implementation of NEXUS, but we will consider releasing one in the future depending on capacity. Thank you.
